name: golangci-lint
on:
  push: {}
  #  branches-ignore:
  #    - main
  pull_request:
    branches:
      - main
permissions:
  contents: read

env:
  GOTELEMETRY: off
  #CGO_ENABLED: 0

jobs:
  lint:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests
    name: lint
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          #go-version: '1.20'
          go-version-file: 'go.mod'
          check-latest: true
      - name: Lint
        run: |
          #golint ./...
          go vet -all ./...
      #- name: golangci-lint
      #  uses: golangci/golangci-lint-action@v8
      #  with:
      #    version: v2.1
