name: Continuous Integration
on:
  push: {}
  #  branches-ignore:
  #    - main
  pull_request:
    branches:
      - main
permissions:
  contents: read

env:
  GOTELEMETRY: off
  #CGO_ENABLED: 0

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          #go-version: 1.19
          go-version-file: 'go.mod'
          check-latest: true
      - run: sudo apt-get install pass gnome-keyring dbus-x11
      - run: go test -race ./...
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          #go-version: 1.19
          go-version-file: 'go.mod'
          check-latest: true
      - run: brew install pass gnupg
      - run: go test -race ./...
